name: Run Jest Tests

on: [push, pull_request]

jobs:
  checklist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Attendre le deploiment
        run: sleep 70
      - run: npm install
      - run: npx blc https://github.com/igor-jean/github_pages -v
